#.travis.yml
sudo: required
dist: trusty
language: node_js
node_js:
  - '11'
before_install:
  - rm -rf node_modules
  - npm install -g ganache-cli@6.2.5
install:
  - npm install
before_script:
  - ganache-cli > /dev/null &
  - sleep 5
script:
  - npm test
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
